### ISSUE TITLE
debops fails common task:  install 'openntpd' --no-install-recommends' failed: /etc/openntpd/ntpd.conf: Permission denied

### ISSUE THREAD

**Issue by 0vermind** [debops/debops-tools#103]
In ubuntu 14.01 ntpd.yml task fails lunching debops playbook.
I think is due to this bug: https://bugs.launchpad.net/ubuntu/+source/openntpd/+bug/458061
I solved the problem as written in comment bug  24 running commands not in the same order but still...

**Comment by drybjed** [comment]
@0vermind Do you had `ntp` package installed before running DebOps playbook on that host? Check with `dpkg -l | grep ntp`. On a Xubuntu desktop install this issue does not show up, did you use server install?

**Comment by 0vermind** [comment]
I don't know I used the docker image based on ubuntu, made by my host (digitalocean). Checking now would be useless, but if this can help you I can create another vps server and check. In any case solving the error was a matter of restart apparmor to purge openntpd and  ntpd package.

**Comment by drybjed** [comment]
@0vermind You mean an Ubuntu virtual machine which could run Docker containers? That would make sense, in that case they probably included `ntpd` as standard. How about this - for these hosts, set `ntp_daemon: 'ntpd'`, in which case `openntpd` won't be installed and DebOps will just go happily with `ntpd` instead. Could you try it and report back?

**Comment by 0vermind** [comment]
I just created a new docker (ubuntu based) image, and i can confirm:

> root@debops:~# dpkg -l | grep ntp
> ii  ntpdate                             1:4.2.6.p5+dfsg-3ubuntu2.14.04.2 amd64        client for setting system time from NTP servers

ntpd is not present, only nptdate. why it's failing?

**Comment by drybjed** [comment]
@0vermind I'm not sure. Did you try setting `ntpd` as default instead of `openntpd`? Also, check if you have `cap_sys_time` capability in the container, by running for example:

```
capsh --print | grep sys_time
```

on the `root` account.

**Comment by 0vermind** [comment]
Current: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend+ep
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend

This is the output.

> How about this - for these hosts, set ntp_daemon: 'ntpd', in which case openntpd won't be installed and DebOps will just go happily with ntpd instead. 

You were talking about setting a var in the playbook? where should I set this?

**Comment by drybjed** [comment]
@0vermind OK, so you have `cap_sys_time` present, that's why DebOps is trying to install `ntp` daemon on the host.

You configure roles using variables in Ansible inventory. For example, if you have this host in your `inventory/hosts` file as `debops`, you can create `inventory/host_vars/debops/ntp.yml` file with contents:

```
ntp_daemon: 'ntpd'
```

This will switch the default daemon from `openntpd` to `ntpd`. Alternatively, you can disable `debops.ntp` role entirely by setting:

```
ntp_daemon: False
```

This way NTP daemon won't be installed and configured at all.

**Comment by 0vermind** [comment]
Thanks for explanation. I'm quite new on Ansible and debops, and as I said before I evaded the bug in another way. I thought you would be interested in knowing that the ntpd playbook need to be adjust if we want to run flowerless on this host.

**Comment by drybjed** [comment]
@0vermind Well, roles can't be configured to work on everything automatically at all times. :-) Usually LXC containers don't have `cap_sys_time` capability enabled which indicates that DebOps should not install any NTP daemon there, since the host itself will manage time. However it seems that in this case the Docker container had this capability enabled for some reason, but using above method you can override that if needed.
