### ISSUE TITLE
Which .ansigenome.conf is used?

### ISSUE THREAD

**Issue by ypid** [debops/debops-tools#133]
https://github.com/debops/debops/tree/master/misc/ansigenome/templates contains the templates but I am unable to reproduce the README.md because `ansigenome_info` is in `meta/ansigenome.yml`.

Related to https://github.com/nickjj/ansigenome/issues/23

**Comment by drybjed** [comment]
Ansible v2 is much more strict on contents of `meta/main.yml` files, that's why I've moved `ansigenome` information to separate files. When I want to generate a README file for a role, I temporarily copy the information back to `meta/main.yml` since `ansigenome` expects the info there.

In `~/.ansigenome.conf` I use [this template](https://github.com/debops/debops/blob/master/misc/ansigenome/templates/DebOps-README.md.j2) which extends the base template.

**Comment by ypid** [comment]
Thanks.

> I temporarily copy the information back to meta/main.yml since ansigenome expects the info there.

I think we should fix this issue in ansigenome don’t you think?

**Comment by drybjed** [comment]
@ypid Sure. I've asked @nickjj about it, but he thinks there might be some issues with the change. Nick?

**Comment by ypid** [comment]
ansigenome is not used by DebOps anymore because of Ansible collections and the DebOps monorepo. Closing so that this repo can be archived eventually.
