### ISSUE TITLE
Bootstrap: Variables from group_vars/all/bootstrap.yml not getting picked up

### ISSUE THREAD

**Issue by zenflip** [debops/debops-tools#202]
# Contributing to DebOps

As of 2017, the DebOps developers [decided to keep all of the DebOps development in one Git tree][monorepo-move]
(an approach called a "monorepo"). Therefore, please do not contribute here.
Please contribute instead in the [debops/debops][debops-monorepo] repository.

Thank you :)

[monorepo-move]: https://lists.debops.org/pipermail/debops-users/2017-August/000078.html
[debops-monorepo]: https://github.com/debops/debops

**Comment by drybjed** [comment]
@cryptoflipper Hi, you can make an issue in the [`debops/debops`](https://github.com/debops/debops/) repository, if you want. It would be nice if you specify what release/branch of DebOps you are using, since there were some big changes in the current `master` branch related to the bootstrap playbook.

**Comment by zenflip** [comment]
Moving to debops/debops
