### ISSUE TITLE
Vagrantfile controller bootstrap

### ISSUE THREAD

**Issue by hleitzell** [debops/debops-tools#48]
I've been attempting to come up with a Vagrantfile that can provide a bootstrapped compatible controller using just your playbooks but there is still a bunch of work to be done (https://github.com/mitchellh/vagrant/issues/3396) to make everything "just-work".
Ideally, Ansible + Vagrant will be cross platform compatible with a local Ansible internally (https://github.com/podarok/vansible) & (https://github.com/mitchellh/vagrant/issues/2103) but that isn't happening just yet.  I've bootstrapped a vagrant host via shell provisionment: "apt-get virtualenv python-dev" => "virtualenv --easyinstall ansible" => "source ansible/bin/activate && pip install --upgrade ansible" and been using that.  

So far, I've been playing around with this for quite some time trying to come up with a decent means to create a local controller via bootstrap.yml since the example Vagrantfile below produces a couple different unattended consequences out of the box.  I'm just throwing this out there to get some thoughts on how to do this elegantly as I think having a local virtual machine locked down with correct cryptography as a controller would be ideal.  

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/debian-7.6"
  config.ssh.forward_agent = true
  config.vm.define "local_controller" do |controller|
    controller.vm.provision "ansible" do |ansible|
      ansible.playbook = "bootstrap/debops-playbooks/playbooks/site.yml"
      ansible.groups = {
        "ansible_controllers" => "local_controller"
      }
    end
  end
end
```

Produces a secret directory structure out of the intended $PWD tree:

``` bash
 tree .vagrant/
.vagrant/
├── machines
│   ├── controller
│   │   └── virtualbox
│   │       ├── action_provision
│   │       ├── action_set_name
│   │       ├── id
│   │       ├── index_uuid
│   │       └── synced_folders
│   ├── default
│   │   └── virtualbox
│   └── local_controller
│       └── virtualbox
└── provisioners
    └── ansible
        ├── inventory
        │   └── vagrant_ansible_inventory
        └── secret
            └── pki
                ├── ca
                │   ├── certs
                │   └── crl
                ├── hosts
                │   └── packer-debian-7.6-amd64
                │       ├── crl
                │       ├── csr
                │       │   └── packer-debian-7.6-amd64.csr
                │       └── signed
                └── wildcard
                    ├── certs
                    ├── crl
                    └── private

24 directories, 7 files
```

Being able to destroy the local controller and bring back up a fresh one while retaining all cryptography (GPG, monkeysphere, x.509 PKI chain, Vault, EncFs) would be rather useful.

**Comment by drybjed** [comment]
Interesting idea. I don't use Vagrant a lot, preferring static KVM boxes, but i see how it might be useful to others.

At the moment I'm storing example inventories in [debops/examples](https://github.com/debops/examples) repository. You can find there an example webserver with `Vagrantfile` included. `webhost-gitusers-dokuwiki/` directory is a complete DebOps + Vagrant example project dir. I haven't tried that Vagrantfile yet, but I think it should work.

Old Vagrant setups from `ginas` can be found here: https://github.com/ginas/ginas/tree/master/contrib/vagrant/inventory-lemp
It was a rather convoluted idea when all inventories were stored together in one directory. But in LEMP setup I've included a controller host (as a `master` which could be used to manage the whole cluster of 3 Vagrant hosts. You could do deployment in two ways:
- `vagrant up --no-provision && vagrant provision` - from the host system which supports Ansible
- `vagrant up` then `ssh 192.168.50.2` (master) and `cd ginas/ ; ./contrib/bootstrap-ansible.sh ; ./site.sh` - when your host does not support Ansible (for example Windows)

When I tried to setup 3 host cluster in Vagrant, I've found that after booting first host Vagrant automatically wanted to provision it, which resulted in error since inventory was configured for three hosts, Ansible didn't find the other two and deployment was a mess. So I avoided Vagrant provisioner on first run to have all three hosts booted and ready. Do you know if that changed, or is still the case?

**Comment by hleitzell** [comment]
I've run into the same problem with Vagrant & Ansible but I need to provide a consistent cross platform solution (Windows, OSX, BSD & Linux) and this is still the best bet.  Over the last several months I've smashed my head into each code base enough to finally figure out how to make them all work together.

My apologies, but as the original work is my employer's and I do not yet have legal permission to submit patches upstream I have to do a clean box solution outside of normal business hours to contribute patches.  It will have to wait until tonight before I can give you patches.

**Comment by drybjed** [comment]
@hleitzell That's fine, take as much time as you need. :-) BTW, if I understand this file tree correctly, `debops.secret` role places roles besides the vagrant internal inventory, that's what you want to have, right?

**Comment by hleitzell** [comment]
Nope, I want the secret roles to be placed in the current directory where vagrant is running as `.vagrant` is usually put into `.gitignore` since it's contents are dynamically generated.

Let me see where my previous work is on this but I think I might have a better solution than I thought for providing a Vagrantfile that provides DebOps with all Debian based OSes to run against.  Otherwise it will have to wait until later tonight.

**Comment by drybjed** [comment]
At the moment secrets are created relative to Ansible inventory, however for Vagrant you could probably just define `secret: '~/secrets'` or whatever path you want in the inventory and `debops.secret` should pick that up. However, at the moment if you want to use encrypted secrets, you will need to modify `debops-padlock` or run its commands manually to set up EncFS. Also, `debops` script which opens/closes encfs will need to be modified somewhat to handle new location.

Why not just use DebOps model of project directories, put you Vagrantfile there and configure vagrant to run ansible with inventory relative to your $PWD? That should let you keep inventory and secrets in one directory (backed with git).

**Comment by htgoebel** [comment]
Please have a look at https://github.com/debops/examples/pull/3 and report back if this is what you'd expect.

**Comment by drybjed** [comment]
There are Vagrant setups available in https://github.com/ganto/ansible-vagrant_debops. I'm closing this issue, if there are still questions about Vagrant setup, let me know.
