### ISSUE TITLE
Ansible Best Practices

### ISSUE THREAD

**Issue by hleitzell** [debops/debops-tools#49]
http://docs.ansible.com/playbooks_best_practices.html

Having DebOps repositories follow a 'develop/stage/production' git branching system would be rather ideal.  It would also allow `debop-init` to structure inventories accordingly and use the repository branch to determine the hosts to run against.

**Comment by hleitzell** [comment]
Mainly saying this as I am going to do my best to integrate DebOps into Ansible Tower with Ansibleworks assistance.  @drybjed What are your thoughts on this?

**Comment by hleitzell** [comment]
I think 'develop' might be unnecessary honestly but I would to think about branching that would be conducive to the changes coming to Galaxy in 1.8 that allow for better control of dependencies: http://docs.ansible.com/galaxy.html

**Comment by drybjed** [comment]
@hleitzell I assume that you mean the git branching model to use thruought DebOps and not Ansible Best Practices that are more about playbook/inventory directory structure?

This is actually hot topic between me and @nickjj on the IRC. BTW: I think IRC might not be a good way to manage DebOps in the long run, since lots of discussions are online and people who don't sit in the channel might miss them. But we have a [Google maling list](https://groups.google.com/forum/#!forum/debops-project) which could probably be better utilized for this purpose. GitHub issues are not really meant for ongoing project discussions either.

As for the git branching model we plan to use:

Roles themselves are very straightforward - main `master` branch and tags every so often. I think a role should be tagged when it's considered stabilized (which doesn't necessarily mean stable) - it's passing Travis tests, hasn't been modified in some time (say, a week to a month, depending on how much other roles depend on it). Then people who use roles directly in their own playbooks can just use the tagged releases and DebOps project can use the `master` branch for ongoing development. For me, I plan to use `master` all the time.

DebOps scripts and playbooks (two separate git projects, remember) are entirely different matter. For some time we were thinking about using git flow for them, and @nickjj even tried it with [rolespec](https://github.com/nickjj/rolespec), however git flow seems very busy and complicated for our needs. Recently published [GitLab flow](https://about.gitlab.com/2014/09/29/gitlab-flow/) seems to be better suited for DebOps playbooks and scripts. So, main `master` branch, which then gets merged to `production` branch and tagged there for stable releases. At least that's easy to manage when it comes to DebOps scripts.

For the main playbooks, things again are complicated by roles. Ansible roles and dependencies system is not designed to handle versioning and dependency resolution, at all (there are voices concerned with it, we will see how it goes). Which means that when we use versioned roles, conflicts need to be managed and resolved centrally and globally - we cannot say that for example nginx role depends on ferm v0.1.2 and postfix depends on ferm v1.3.0, because then things will break. We have a Galaxy requirements file which is designed to be a central place to maintain role versioning information, but then how do we handle releases of the DebOps playbooks themselves? What does it mean to have a "stable" release? It probably means that all roles included are versioned and Galaxy requirements file points each role for a certain tag, because otherwise we cannot ensure stability.

Well, that's the gist of it anyway. As you probably notices, stabilization with this project won't be easy, but we are working on it. :-) I plan to start tagging roles in the near future, as for the playbooks and scripts, we will see how it goes.

**Comment by hleitzell** [comment]
This is much better if I just hop on IRC.  I've stayed away since the 90s as I ended up wasting chunks of life on it.
